blogapp/models.py
from . import db, bcrypt_app, login_manager
from datetime import datetime
from sqlalchemy.ext.hybrid import hybrid_property
from flask_login import UserMixin
from mistune import markdown
import bleach
import re


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80), nullable=False)
    content = db.Column(db.Text, nullable=False)
    content_html = db.Column(db.Text)
    content_summary = db.Column(db.Text)
    summary = db.Column(db.Text)
    num_of_view = db.Column(db.Integer, default=0)
    pub_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    up_date = db.Column(db.DateTime, default=datetime.utcnow)
    tag_id = db.Column(db.Integer, db.ForeignKey('tag.id'),
                            nullable=False)

    tag = db.relationship('Tag',
                               backref=db.backref('posts', lazy=True))

    def __repr__(self):
        return '<Post> %r' % self.title


    def to_dict(self):
        post_dict = {}
        post_dict['title'] = self.title
        post_dict['content'] = self.content
        post_dict['content_html'] = self.content_html
        post_dict['content_summary'] = self.content_summary
        post_dict['num_of_view'] = self.num_of_view
        post_dict['pub_date'] = self.pub_date
        post_dict['up_date'] = self.up_date
        post_dict['tag_id'] = self.tag_id
        return post_dict


    @staticmethod
    def add(post=None, title=None, content=None, tag=None):
        if post is None:
            post = Post(title=title, content=content, tag=tag)
        try:
            db.session.add(post)
            db.session.commit()
        except:
            print('Fail')


    @staticmethod
    def delete(post=None, id=None):
        if post is None:
            post = Post.query.filter_by(id=id).first()
        db.session.delete(post)
        db.session.commit()

    @staticmethod
    def on_changed_content(target, value, oldvalue, initiator):
        allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                        'h1', 'h2', 'h3', 'p', 'img']
        attrs = {
            '*': ['class'],
            'img': ['src'],
            'a': ['href'],
        }
        target.content_html = bleach.linkify(bleach.clean(
            markdown(value), tags=allowed_tags, strip=True, attributes=attrs))
        pattern = re.compile(r'<[^>]+>', re.S)
        summary = pattern.sub('', target.content_html)
        summary = (summary[0:40] + '...') if len(summary) >= 40 else summary
        target.content_summary = summary

db.event.listen(Post.content, 'set', Post.on_changed_content)


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)

    def __repr__(self):
        return '<Tag %r>' % self.name

    @staticmethod
    def add(tag=None, name=name):
        if tag is None:
            tag = Tag(name=name)
        try:
            db.session.add(tag)
            db.session.commit()
        except:
            print('Fail')


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)

    @hybrid_property
    def password(self):
        return self._password

    @password.setter
    def password(self, plaintext):
        self.password_hash = bcrypt_app.generate_password_hash(plaintext).decode('utf-8')

    def verify_password(self, password_input):
        return bcrypt_app.check_password_hash(self.password_hash,
                                              password_input)

    def __repr__(self):
        return '<User %r>' % self.username

    def __init__(self, username, password):
        self.username = username
        self.password = password

    @staticmethod
    def add(user=None, username=None, password=None):
        if user is None:
            user = User(username=username, password=password)
        try:
            db.session.add(user)
            db.session.commit()
            print('success')
        except:
            print('Fail')
            pass


@login_manager.user_loader
def load_user(userid):
    return User.query.get(userid)

blogapp/forms.py
from flask_wtf import FlaskForm as Form
from wtforms import BooleanField, StringField, PasswordField, validators
from wtforms import TextAreaField, SubmitField, SelectField
from flask_pagedown.fields import PageDownField


class LoginForm(Form):
    username = StringField('Username', [validators.Length(min=3, max=30)])
    password = PasswordField('Password', [validators.DataRequired()])
    submit = SubmitField('Log in')


class RegisterForm(Form):
    username = StringField('Username', [validators.Length(3, 30)])
    email = StringField('Email', [validators.DataRequired(), validators.Email()])
    password = PasswordField('Password', [validators.DataRequired()])
    submit = SubmitField('Register')


class PostForm(Form):
    title = StringField('Title', [validators.DataRequired()])
    content = PageDownField('Content', [validators.DataRequired()])
    tag = SelectField('Tag', coerce=int)
    submit = SubmitField('add post')


class TagForm(Form):
    tag = StringField('Tag', [validators.DataRequired()])
    submit = SubmitField('add tag')

blogapp/Main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

blogapp/Main/views.py
from flask import render_template, redirect, flash, url_for, request
from flask import current_app
from ..models import Post
from .. import db
from . import main


@main.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.pub_date.desc()).paginate(
        page, per_page=current_app.config['POST_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    return render_template('index.html', posts=posts, pagination=pagination)


@main.route('/articles/<article_id>')
def article_details(article_id):
    post = Post.query.filter_by(id=article_id).first()
    post.num_of_view += 1
    db.session.commit()
    return render_template('article_details.html', post=post)


@main.route('/about')
def about():
    return render_template('about.html')


@main.route('/archives')
def archives():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.pub_date.desc()).paginate(
        page, per_page=current_app.config['ARCHIVE_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    print(posts[0].pub_date.date())
    return render_template('archives.html', posts=posts, pagination=pagination)


## Error Handler Views

@main.app_errorhandler(403)
def forbidden(e):
    return render_template('error.html', error=403), 403


@main.app_errorhandler(404)
def page_not_found(e):
    return render_template('error.html', error=404), 404


@main.app_errorhandler(500)
def internal_server_error(e):
    return render_template('error.html', error=500), 500

blogapp/User/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)
auth = Blueprint('auth', __name__)

from . import views

blogapp/User/views.py
from flask import render_template, request, flash, redirect, url_for
from flask import jsonify, current_app
from flask_login import login_user, login_required, logout_user, current_user
from ..forms import LoginForm, RegisterForm, PostForm, TagForm
from ..models import User, Post, Tag
from .. import db
from . import auth, user
from datetime import datetime


@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is not None and user.verify_password(form.password.data):
            print(user)
            login_user(user)
            flash('login success')
            return redirect(url_for('user.index'))
        else:
            flash('Wrong!', 'danger')

    return render_template('user/login.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('logout success')
    return redirect(url_for('main.index'))


@auth.route('/register', methods=['GET', 'POST'])
@login_required
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        User.add(username=form.username.data,
                      password=form.password.data)
        flash('register success')
        return redirect(url_for('auth.login'))

    return render_template('user/register.html', form=form)


@user.route('/')
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.order_by(Post.pub_date.desc()).paginate(
        page, per_page=current_app.config['POST_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    return render_template('user/index.html', posts=posts, 
        pagination=pagination, name=current_user.username)


@user.route('/addpost', methods=['GET', 'POST'])
@login_required
def add_post():
    tags = Tag.query.all()
    tags_list = [(tag.id, tag.name) for tag in tags]
    form = PostForm()
    form.tag.choices = tags_list

    if form.validate_on_submit():
        post_tag = tags_list[int(form.tag.data)-1][1]
        tag = Tag.query.filter_by(name=post_tag).first()
        post = Post(title=form.title.data, content=form.content.data, tag=tag)
        Post.add(post=post)
        flash('add post success')
        return redirect(url_for('user.index'))

    return render_template('user/addpost.html', form=form, tags=tags)


@user.route('/addtag', methods=['GET', 'POST'])
@login_required
def add_tag():
    form = TagForm()

    if form.validate_on_submit():
        if Tag.query.filter_by(name=form.tag.data).first() is None:
            tag = Tag(name=form.tag.data)
            Tag.add(tag=tag)
            flash('add tag sucess')
        else:
            flash('The tag "%r" already exists' % form.tag.data)

        return render_template('user/addtag.html', form=TagForm())

    return render_template('user/addtag.html', form=form)


@user.route('/deletepost')
@login_required
def delete_post():
    try:
        post_id = request.args.get('post_id', type=int)
    except:
        flash('delete post failed')

    Post.delete(id=post_id)
    flash('delete post secess')
    return redirect(url_for('user.index'))


@user.route('/editpost', methods=['GET', 'POST'])
@login_required
def edit_post():
    try:
        post_id = request.args.get('post_id', type=int)
    except:
        flash('edit post failed')

    post = Post.query.filter_by(id=post_id).first()
    tags = Tag.query.all()
    tags_list = [(tag.id, tag.name) for tag in tags]
    form = PostForm()
    form.tag.choices = tags_list

    if form.validate_on_submit():
        post_tag = tags_list[int(form.tag.data)-1][1]
        tag = Tag.query.filter_by(name=post_tag).first()
        post.title = form.title.data
        post.content = form.content.data
        post.tag = tag
        post.up_date = datetime.utcnow()
        db.session.commit()
        flash('post update sucess')
        return redirect(url_for('user.index'))

    form.title.data = post.title
    form.content.data = post.content
    form.tag.data = post.tag_id - 1
    return render_template('user/addpost.html', form=form)


@user.route('/todict', methods=['GET', 'POST'])
@login_required
def to_dict():
    try:
        post_id = request.args.get('post_id')
    except:
        flash('to dict failed')

    post = Post.query.filter_by(id=post_id).first()
    post_dict = post.to_dict()
    return str(post_dict)

blogapp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_pagedown import PageDown


db = SQLAlchemy()
bcrypt_app = Bcrypt()
pagedown = PageDown()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'

def create_app():
    app = Flask(__name__,
                instance_relative_config=True,
                static_url_path='/old/static')

    app.config.from_object('config')
    app.config.from_pyfile('config.py')

    db.init_app(app)
    bcrypt_app.init_app(app)
    pagedown.init_app(app)
    login_manager.init_app(app)

    from .User import user, auth
    from .Main import main

    app.register_blueprint(user, url_prefix='/old/user')
    app.register_blueprint(auth, url_prefix='/old')
    app.register_blueprint(main, url_prefix='/old')

    # if db.init_app called after the blueprint register ,
    # codes below is needed
    # with app.app_context():
    #     db.create_all()

    return app

blogapp/templates/about.html
{% extends "layout.html" %}

{% block body %}

<div class="container">
    <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h2>About</h2>
        <br><br><br>
        <ul>
            <li>没空打比赛的社畜</li><br>
        </ul><br>
        <p>邮箱: <a class="text-info" href="mailto:logjian@gmail.com">logjian@gmail.com</a></p><br>
        <p><a class="text-info" href="https://github.com/marryjianjian/flaskblog" target="_blank">这个博客</a>开发不动了，直接换<a class="text-info" href="https://blog.fflush.me">新的<a/>了</p>
    </div>
    <div class="col-md-2"></div>
</div>
<br><br>

{% endblock %}

blogapp/templates/archives.html
{% extends "layout.html" %}
{% from "widget.html" import pagination_widget %}
{% block body %}

<div class="container">
    <div class="row">
    <div class="col-md-2"></div>
    <div class="card mb-3 col-md-8 text-center">
        <ul class="list-group list-group-flush">
            {% for post in posts %}
            <li class="list-group-item text-left">
                {{ post.pub_date.date() }}&nbsp;&nbsp;
                    <a href="{{ url_for('main.article_details', article_id=post.id) }}" class="text-secondary">{{ post.title }}</a>                
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-md-2"></div>
    </div>
</div>
<br><br>
{{ pagination_widget(pagination, '.archives') }}

{% endblock %}

blogapp/templates/article_details.html
{% extends "layout.html" %}

{% block title %}
{{ super() }}
--{{ post.title }}
{% endblock %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <br>
        <div class="col-md-8 postpicture">
            <h1 class="text-center">{{ post.title }}</h1><br><br>
            {{ post.content_html|safe }}
        </div>
        <br>
        <div class="col-md-2"></div>
    </div>
</div>

{% endblock %}

blogapp/templates/error.html
{% extends "layout.html" %}

{% block body %}

<style>
    .error {
        float: none;
        display: block;
/*        margin-bottom: auto;*/
        margin-left: auto;
        margin-right: auto;
    }
</style>

<h2 class="col-xs-6 col-sm-6 col-md-6 col-lg-4 error display">Something Wrong.  {{ error }}</h2>

{% endblock %}

blogapp/templates/index.html
{% extends "layout.html" %}
{% from "widget.html" import pagination_widget %}
{% block body %}

<div class="container">
    <div class="row">
    {% for post in posts %}
    <div class="col-md-2"></div>
    <div class="card mb-3 col-md-8 text-center">
        <div class="card-body">
            <h4 class="card-title">{{ post.title }}</h4>
            <p class="card-text">{{ post.content_summary }}</p>
            <a href="{{ url_for('main.article_details', article_id=post.id) }}" class="btn btn-light btn-sm">more</a>
        </div>
    </div>
    <div class="col-md-2"></div>
    {% endfor %}
    </div>
</div>
<br><br>
{{ pagination_widget(pagination, '.index') }}

{% endblock %}

blogapp/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSS files -->
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/prism.css') }}">
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/utils.css') }}">

    <link rel="shortcut icon" href="{{ url_for('static', filename='img/f.ico') }}">

  <title>Just {% block title %}{% endblock %}</title>

</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <a class="navbar-brand" href="{{ url_for('main.index') }}">JustJian</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.archives') }}">archives</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
      </li>
    </ul>
  </div>
    {% if current_user.is_authenticated %}
    <nav class="nav justify-content-end">
        <li class="nav-item">
            <li class="nav-item dropdown" style="margin-right: 60px">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ current_user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{{ url_for('user.index') }}">Manage</a>
                  <a class="dropdown-item" href="{{ url_for('user.add_post') }}">Add Post</a>
                  <a class="dropdown-item" href="{{ url_for('user.add_tag') }}">Add Tag</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{{ url_for('auth.logout') }}">Logout</a>
                </div>
                </li>
        </li>
    </nav>
    {% endif %}
</nav>
    <br>
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">{{ message }}</div>
    {% endfor %}
    {% block body %}
    {% endblock %}
    </div>

    {% block scrpts %}
    {% endblock %}
    <br><br><br><br>
    <footer class="footer">
    <div class="container text-center">
      <span class="text-muted text-center">Copyright &copy; 2019 Powered by <a href="http://flask.pocoo.org/" target="_blank">Flask</a></span>
    </div>
    </footer>
    <script src="{{ url_for('static', filename='js/prism.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>
</html>

blogapp/templates/show_entries.html
{% extends "layout.html" %}
{% block body %}
{% if session.logged_in %}
<form action="{{ url_for('add_entry') }}" method=post class=add-entry>
  <dl>
    <dt>Title:
      <dd><input type=text size=30 name=title>
        <dt>Text:
          <dd><textarea name=text rows=5 cols=40></textarea>
            <dd><input type=submit value=Share>
  </dl>
</form>
{% endif %}
<ul class=entries>
  {% for entry in entries %}
  <li><h2>{{ entry.title }}</h2>{{ entry.text|safe }}
    {% else %}
  <li><em>Unbelievable. No entries here so far</em>
    {% endfor %}
</ul>
{% endblock %}

blogapp/templates/widget.html
{% macro pagination_widget(pagination, endpoint) %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="{% if not pagination.has_prev %} disabled {% endif %} page-item" >
            <a class="page-link" href="{% if pagination.has_prev %}
            {{ url_for(endpoint, page=pagination.page-1, **kwargs) }}
            {% else %} # {% endif %}">&laquo;</a>
        </li>
        {% for p in pagination.iter_pages() %}
            {% if p %}
                <li class="{% if p == pagination.page %} active {% endif %} page-item">
                    <a class="page-link" href="{{ url_for(endpoint, page=p, **kwargs) }}">{{ p }}</a>
                </li>
            {% else %}
            <li class="page-item disabled"><a href="#">&hellip;</a></li>
            {% endif %}
        {% endfor %}
        <li class="{% if not pagination.has_next %} disabled {% endif %} page-item">
            <a class="page-link" href="{% if pagination.has_next %}
            {{ url_for(endpoint, page=pagination.page+1, **kwargs) }}
            {% else %} # {% endif %}">&raquo;</a>
        </li>
    </ul>
</nav>
{% endmacro %}